#!/bin/sh -f
#--------------------------------------------------------------------------------------
# THE RUN FILE created by Cadence Extraction Quantus UI Version 23.1.0-p075
#--------------------------------------------------------------------------------------

qrc  -log_file /home/saul/projects/ASKA/PvsLVS/constant_gm/svdb/qrc.constant_gm.log -cmd /home/saul/projects/ASKA/PvsLVS/constant_gm/svdb/qrc.constant_gm.ccl 
