#!/bin/sh -f
#--------------------------------------------------------------------------------------
# THE RUN FILE created by Cadence Extraction Quantus UI Version 23.1.0-p075
#--------------------------------------------------------------------------------------

qrc  -log_file /home/saul/projects/ASKA/PvsLVS/hvswitch5/svdb/qrc.hvswitch5.log -cmd /home/saul/projects/ASKA/PvsLVS/hvswitch5/svdb/qrc.hvswitch5.ccl 
