#!/bin/sh -f
#--------------------------------------------------------------------------------------
# THE RUN FILE created by Cadence Extraction Quantus UI Version 23.1.0-p075
#--------------------------------------------------------------------------------------

qrc  -log_file /home/saul/projects/ASKA/PvsLVS/dac6b_amp_n2/svdb/qrc.dac6b_amp_n2.log -cmd /home/saul/projects/ASKA/PvsLVS/dac6b_amp_n2/svdb/qrc.dac6b_amp_n2.ccl 
